image: docker:19.03.12

services:
  - docker:19.03.12-dind
  
.ssh_preparation: &ssh_preparation
  before_script:
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /etc/ssh/ssh_config'
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

stages:
  - build
  - deploy

before_script:
  -  docker login -u 4lirez4 -p Y8A68hsb9n
build:
  stage: build
  only: 
    - main
  # when: manual
  script:
    - docker build --cache-from 4lirez4/tasnim:panel  --tag 4lirez4/tasnim:panel .
    - docker push 4lirez4/tasnim:panel

deploy:
  stage: deploy
  only:
    - master
  <<: *ssh_preparation
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST "sudo su;sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD ;cd '$DEPLOY_PATH';sudo git pull;sudo docker-compose pull ;sudo docker-compose up -d; sleep 3;sudo docker-compose ps"

  when: manual
  # tags:
  #   - deploy
